### ISSUE TITLE
Allow TrainG2PModelJob to use g2p_path from another sisyphus job

### ISSUE THREAD

**Issue by mattiadg** [rwth-i6/i6_core#121]
https://github.com/rwth-i6/i6_core/blob/a76d943bb227e6f73be6e648b69b1d1426f19cf2/g2p/train.py#L29

In the vision of making this software portable among different configuration, it is useful to pass as `g2p_path` and `g2p_python` paths from a venv created from another Sisyphus job. In this case, as far as I understand, the input type would be `DelayedBase`, which is not currently supported.

**Comment by curufinwe** [comment]
It should be enough to wrap `self.g2p_python` and `self.g2p_path` with `str` in these two lines here: https://github.com/rwth-i6/i6_core/blob/main/g2p/apply.py#L64

**Comment by mattiadg** [comment]
should it be done conditionally to the input type or `str` doesn't change anything for Path?
