### ISSUE TITLE
Checkpoint not compatible with delayed_op

### ISSUE THREAD

**Issue by mattiadg** [rwth-i6/i6_core#125]
The [Checkpoint](https://github.com/rwth-i6/i6_core/blob/34f82dd09f932da9d6c28d9781d7f20d4df888af/returnn/training.py#L38) class can be used to point to checkpoints in a recognition setup that can be in a different directory than the training setup.

In that case, the only solution I could think of is to wrap the checkpoint paths into some `DelayedBase` subclass, but it's not supported by Checkpoint:
```
     51 
     52     def _sis_hash(self):
---> 53         return self.index_path._sis_hash()
        self.index_path._sis_hash = undefined
     54 
     55     def __str__(self):

AttributeError: 'DelayedFormat' object has no attribute '_sis_hash'
```

Is this a legacy decision or intentional?

**Comment by JackTemaki** [comment]
> different directory
So you mean the training comes from a completely different Sisyphus setup? While this is often not a good idea this is not a problem here.

Why do you want to use DelayedFormat? Can you not just give the absolute path to the training checkpoint from the "other" Sisyphus setup?

**Comment by michelwi** [comment]
>the only solution I could think of is to wrap the checkpoint paths into some DelayedBase subclass

What about Path object instead?
```
my_checkpoint = Checkpoint(ckpt_path="/path/to/model/dir/epoch.120", 
                           index_path=Path("/path/to/model/dir/epoch.120.index"))
```

**Comment by mattiadg** [comment]
I think I didn't get when Delayed is needed

**Comment by michelwi** [comment]
Delayed is needed, when the content of a variable is dependent on a different Job and therefore is/can not be known at the time of graph creation.

Examples are:
* best epoch of a training run 
* path to the beast checkpoint (would be DelayedAdd of model_dir + best_epoch)
* best LM scale after optimization

**Comment by JackTemaki** [comment]
> I think I didn't get when Delayed is needed

A "Delayed" object is needed if you want to combine a "dynamic" result of a sisyphus job (which can be a tk.Variable or a tk.Path) with some static content from your graph code. 

There are only very few cases where this is necessary, a typical example might be something related to the PipelineJob.

So lets say you have a job that returns a certain integer value as tk.Variable, but you always want to add 1 to it.
Then you could write `new_variable = DelayedAdd(old_variable, 1)`

This would mean `new_variable` would be hashed as combination of the old one and the 1, and the addition would only be executed in when calling `new_variable.get()` inside the job where `new_variable` is used.

**Comment by JackTemaki** [comment]
> Examples are:
> 
>     * best epoch of a training run
> 
>     * path to the beast checkpoint (would be DelayedAdd of model_dir + best_epoch)
> 
>     * best LM scale after optimization

Example 1 and 3 can be solved without using a `Delayed` object! Because here no combination takes place

**Comment by curufinwe** [comment]
Closed due to inactivity. Reopen if still relevant.
