### ISSUE TITLE
SelfNoiseCorpusJob / ChangeCorpusSpeedJob output_name convention + non-determinism

### ISSUE THREAD

**Issue by curufinwe** [rwth-i6/i6_core#13]
SelfNoiseCorpusJob and ChangeCorpusSpeedJob have outputs whose names do not match the new convention. In addition SelfNoiseCorpusJob creates a random seed if called without a seed (this adds non-determinism).

Assigning it to you @JackTemaki so you can also update your setups with the new names.

**Comment by JackTemaki** [comment]
Resolved with #15
