### ISSUE TITLE
cached_alignment_flow doesn't connect the alignment nodes to the existing network

### ISSUE THREAD

**Issue by mattiadg** [rwth-i6/i6_core#145]
https://github.com/rwth-i6/i6_core/blob/d27320747b0d7ebe40b8fec6a96cdacb7a961aa5/mm/flow.py#L78-L95
you can see  that "alignment-cache" is connected to "network:alignments" but not to the previous network.

**Comment by michelwi** [comment]
I think this is the intended behavior. The "alignment-cache" node acts as a source, independent of the feature flow, as it reads the alignment from the provided file.
The alignment-node only needs the features as inputs when it is computing the alignment on the fly, e.g. like in the function `alignment_flow`  https://github.com/rwth-i6/i6_core/blob/d27320747b0d7ebe40b8fec6a96cdacb7a961aa5/mm/flow.py#L54-L62

**Comment by mattiadg** [comment]
So, what it does is to provide a double channel, so that it can be used for
example to use the alignment with different features?

Il gio 16 set 2021, 23:12 michelwi ***@***.***> ha scritto:

**Comment by michelwi** [comment]
Yes. Alignments are - in principle - independent from the features that were used to compute them (e.g. generate an alignment with GMM with mfcc features and use it to train a NN with gammatone features).
This node combines an existing alignment with any features, including but not limited to the original ones.
