### ISSUE TITLE
Any plans for testing?

### ISSUE THREAD

**Issue by mattiadg** [rwth-i6/i6_core#147]
Are you thinking about adding tests to this? 
Considering that from time to time some bugs emerge, or the behavior of one class is not clear, or even sometimes "this could never work", what do you think about adding tests every time one of these, or other, problems arise?

I know that the coupling with sisyphus can create some problems for testing, but the core of the `run` method, with no IO from/to hard disk can be tested.

**Comment by curufinwe** [comment]
For some of the smaller python only jobs we could do it. But everything that also includes RASR will be challenging to build a testing environment for.
