### ISSUE TITLE
Why does the flow network not need the generic-convert-vector-s16-to-vector-f32 node for ffmpeg?

### ISSUE THREAD

**Issue by Nintendo-Wei** [rwth-i6/i6_core#169]
I got an error `configure datatype "vector-s16" failed (expected "vector-f32")` extracting features from MP3 audio files using `ffmpeg` and found that from line 111-121 in `i6_core/features/common.py` `if input_node_type == "ffmpeg"` the `generic-convert-vector-s16-to-vector-f32` is not added to the flow network. 
What could be the reasons for this and is it possible to fix the error without changing the code there?
Thanks in advance!

**Comment by curufinwe** [comment]
The ffmpeg flow returns the datastructure that the file is coded in. If the file is coded using unsigned shorts it will return u16 and if it's coded with floats it will return f32. Probably the most elegant thing to do here is to enforce a configurable output type in the flow node.

**Comment by mattiadg** [comment]
Are there any plans to solve this? I've also got in the same error.
@curufinwe do you think to pass the output type regardless of the audio format?

**Comment by JackTemaki** [comment]
I think we can close this due to inactivity, if there is every the need again to update the samples flow to do more controlled type conversion we can re-open this or a new issue.
