### ISSUE TITLE
corpus naming consistency

### ISSUE THREAD

**Issue by christophmluscher** [rwth-i6/i6_core#171]
At the moment, we do not seem to have a clear definition on how to name different corpus data representations. My suggestion would be something like:
`corpus_key` -> `str` (basically corpus identifier)
`corpus_object` -> `CorpusObject`
`corpus_file` -> `str` (would be filepath)
`corpus` -> `Path`
I am open for suggestions on this.

This mainly concerns the `meta/system.py` and `i6_experiments/common/{hybrid,rasr}`.
The classes in `i6_experiments` build upon `meta/system.py`. Applying the naming convention to `i6_experiments` should not be an issue. The question is do we apply the naming convention to `meta/system.py` directly or are there some concerns since all systems which use `meta/system.py` would need to adapt to this change?

**Comment by michelwi** [comment]
I fully agree with 

> `corpus_key` -> `str` (basically corpus identifier)
> `corpus_object` -> `CorpusObject`

nut sure if `corpus_file` -> `str` is so obvious or if also the `Path` object pointing to the location could be meant here. Could this be handled interchangeably? Would we even ever want to use the `str` of the file location outside of run methods?

> `corpus` -> `Path`

Maybe `corpus_path` to make it clear a `Path` object is used. To avoid confusion I would never use `corpus` without qualifier at all.

**Comment by JackTemaki** [comment]
> Would we even ever want to use the `str` of the file location outside of run methods?

Definitely no, this should never be the case


> > `corpus` -> `Path`
> 
> Maybe `corpus_path` to make it clear a `Path` object is used. To avoid confusion I would never use `corpus` without qualifier at all.

yes, but for me also `corpus_file` would mean a `tk.Path` object, as a str file path usually means your setup is wrong ;)

**Comment by michelwi** [comment]
Agreed. So the updated suggestion would be

`corpus_key` -> `str` (basically corpus identifier)
`corpus_object` -> `CorpusObject`
`corpus_file` -> `Path` (would be filepath)
`corpus_config` -> `RasrConfig` describing the corpus

`corpus` any, but usage is discouraged
