### ISSUE TITLE
missing Job and function

### ISSUE THREAD

**Issue by christophmluscher** [rwth-i6/i6_core#172]
in `meta.system.py` in function `wcts`: https://github.com/rwth-i6/i6_core/blob/main/meta/system.py#L528

there is a Job and a function missing: `WordConditionedTreeSearchJob` and `pruning_config`. They should be in `recognition`, but they are not. At least I can't find them. I don't need them but maybe we could add them or remove the function `wcts`!?

@curufinwe maybe you know where they are?

**Comment by curufinwe** [comment]
This is the old recognizer. I don't think anybody except me has used it in the last 7-8 years or so. We can remove it completely.
