### ISSUE TITLE
upper in ExtractOovWordsFromCorpusJob

### ISSUE THREAD

**Issue by christophmluscher** [rwth-i6/i6_core#177]
In `ExtractOovWordsFromCorpusJob` we upper case for every and all lemmas. This causes problems for german because python treats "ß" like this: `"ß".upper() -> SS".
I think this should be this should be configurable via job parameter. Add param to sis hash ignore? has this Job been used?
@curufinwe @JackTemaki @michelwi

**Comment by michelwi** [comment]
> I think this should be this should be configurable via job parameter. 

I think default should be to not change the casing and have a `TextToUpperJob` or `PipelineJob(["sed 's/[:lower:]/[:upper:]/g')` if need be. Now that it already is that way, adding a configurable parameter is the goto solution.

> has this Job been used?

Don't know, not by me. 

> Add param to sis hash ignore? 

If in doubt yes.

**Comment by JackTemaki** [comment]
@christophmluscher Is this resolved?

**Comment by christophmluscher** [comment]
fixed #184
