### ISSUE TITLE
passing dictionaries as hidden function parameters.

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/i6_core#21]
I noticed that in the code we often define dictionaries containing some values that are used as parameters for some function calls after being passed through multiple locations (e.g. `samples_options` -> `sample_flow()`).

I think this would be nicer (also in terms of autocompletion) if we would use something like a `SamplesOptions` object in which it is clearly defined what variables are expected.

Otherwise it is not clear from the outside what variables can be used, and you need to traverse the full code to see what you can actually do.

**Comment by JackTemaki** [comment]
I would not change the function itself, but rather do something like `sample_flow(**samples_options.as_dict())`

**Comment by curufinwe** [comment]
OK

**Comment by curufinwe** [comment]
@JackTemaki any update on this?

**Comment by curufinwe** [comment]
Close due to inactivity.
