### ISSUE TITLE
Filter out empty g2p translations

### ISSUE THREAD

**Issue by mattiadg** [rwth-i6/i6_core#213]
I found out that our g2p tool can produce empty pronunciations. When the g2p output is transformed into a lexicon, the corresponding entry does not have a `<phon>` tag and this causes a failure of RASR when the lemma is encountered and should be transformed into its pronunciation.

What do you think it should be the best way to create a clean lexicon? Introduce a new job that filters out empty-pronunciation lemmas, or maybe add this option in other jobs like `G2POutputToBlissLexiconJob`?

**Comment by michelwi** [comment]
quick n dirty: run the output of g2p apply job through a pipeline job that filters out lines with just one word (e.g. with awk)
more clean an nice: add an option `filter_empty_outputs` to the apply g2p job.
