### ISSUE TITLE
AdvancedTreeSearchJOb make rqmt default depend on TF mode

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/i6_core#244]
When doing recognition with a Tensorflow based model, the CPU load will be slightly above 1.0 even if only one CPU is requested in the SGE, according to @christophmluscher 

Thus, the `self.rqmt` should be set to a minimum of two if the a TF node is used.

Also see #238

**Comment by christophmluscher** [comment]
https://github.com/tensorflow/tensorflow/issues/34415

this seems to be a TF problem. maybe there is already fix for this. I ll look into this

**Comment by JackTemaki** [comment]
I am closing this, TF is slowly getting deprecated, and Slurm enforces a minimum CPU set of 2 for machines with hypercores.
