### ISSUE TITLE
Moving of bpe to label restarts ReturnnTrainBpeJob

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/i6_core#255]
#231 broke a job of mine. The hash stayed the same but sisyphus wants to redo the job with a new path (which now includes `label` instead of `bpe`).
Are there any changes to my setup necessary?

**Comment by michelwi** [comment]
Maybe I was wrong with this comment and we would need the original solution.
https://github.com/rwth-i6/i6_core/pull/231#discussion_r837412495

**Comment by Atticus1806** [comment]
Yes this does fix it. Do we need @JackTemaki to comment on this since it was his PR or shall I just open a new one with changing this?
