### ISSUE TITLE
`CorpusToStmJob` has unused input parameters

### ISSUE THREAD

**Issue by christophmluscher** [rwth-i6/i6_core#281]
As far as I can see parameters `exclude_non_speech`, `remove_punctuation` and `fix_whitespace` are not used in the job, but they are set to `True`.
I am not sure how to fix this without changing the hash. If somebody has an idea, feel free to comment

**Comment by michelwi** [comment]
The original implementation still had the functionality.
https://p.i6.informatik.rwth-aachen.de/diffusion/ASR/browse/master/corpus/__init__.py$159

maybe we can restore it?

**Comment by christophmluscher** [comment]
addressed in #282 

@michelwi is something from the original implementation missing?! I dont think so.. so I would leave. either way, I think we should than do a new isse and PR
