### ISSUE TITLE
Adding invert option for all jobs taking segment files

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/i6_core#30]
Some jobs can use given segments as "blacklist" instead of a "whitelist" with an `invert_match` parameter.

This might be added to all Jobs that take segments.

**Comment by curufinwe** [comment]
:+1:

**Comment by mattiadg** [comment]
I think that this has already been done, but I think that a more descriptive name such as `is_whitelist` or `is_blacklist` would make the read easier. I was reading `FilterCorpusBySegmentsJob` and I had to read the code to understand what `invert_match` is.
I mean, at this point there is nothing that tells what the "direct" match that you are inverting is, it could be either ways.

**Comment by michelwi** [comment]
That is a good comment! I would go further and propose we get rid of the invert option altogether and each job should accept both `blacklist` and `whitelist` and select accordingly if a file is given.
Maybe assert that at least one is given if the job would be a no-op otherwise.

**Comment by curufinwe** [comment]
Closed due to inactivity.
