### ISSUE TITLE
Hash-bug in ReturnnComputePriorJob

### ISSUE THREAD

**Issue by michelwi** [rwth-i6/i6_core#306]
The same problem as discussed in https://github.com/rwth-i6/i6_core/issues/274 happens also in the ReturnnComputePriorJob:
during config creation the `checkpoint.ckpt_path` is used instead of using only the `checkpoint`.

https://github.com/rwth-i6/i6_core/blob/63a6d691f3fc8a270f87ee656c1437fc4ed01b59/returnn/extract_prior.py#L218

Should we do a V2 Job here as well?
Are there any other improvements we should tackle while were at it?

**Comment by JackTemaki** [comment]
I vote for V2 as well, I do not see any sense in treating this differently.

**Comment by JackTemaki** [comment]
I currently do not have a pipeline that uses this, but @christophmluscher  and @vieting have, so maybe they have ideas for other improvements. As I am on vacation the next two weeks, you have my approval to just fix this job in the same way as the ReturnnSearchJob.

**Comment by vieting** [comment]
I don't have setups using this job, so either way of handling is fine for me. Agree though, that there's no reason to treat it differently than #274 if setups exist, e.g. by @christophmluscher.

**Comment by christophmluscher** [comment]
I have a setup with this job. I can do the PR and also add a test.

I would also vote for V2. Ill check for improvements as well.

@Marvin84 are you using this job as well?

**Comment by Marvin84** [comment]
> @Marvin84 are you using this job as well?

No, I have my own prior computation job which can be used also context-dependent case.

**Comment by JackTemaki** [comment]
Solved with #316
