### ISSUE TITLE
ScliteJob cant align - no error

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/i6_core#309]
For scoring I use the ScliteJob but noticed strange behavior:

The job printed this in the log:
```
 Performing alignments for file '5536-43363-0015'.
        1 of 1 Segments For Channel 1. align_ctm_to_stm: File identifiers do not match but continuing. ref file/channel '5536-43363-0016' '1', next hyp '6241-66616-0016' '1'.
``` 

I found that this is caused by a faulty input from the LatticeToCtmJob (somehow the formatting is messed up), rerunning the Lattics job fixed this. Unfortunately I am not able to reconstruct what went wrong in the Lattice Job, whether I restarted it after some IO crash or smth.
But the big big Problem I see here is:
The ScliteJob did not crash! Instead I had an unusually high WER (35% instead of the expected WER arround 10%), thats how I found the issue. So for some reason probably the job still evaluates on the wrong sequences. But now imagine this only happens for a few sequences. Small enough that the error does not show strike the eye but still wrong. Lets say a new technique is tried and the new WER is 10.0 instead of 9.5. This I think is really dangerous.
Am I overlooking something here or should the ScliteJob crash when this happens?

**Comment by michelwi** [comment]
Do you still have the faulty CTM file (or can reproduce one) so we can use it to debug/test this further?

since we use 
https://github.com/rwth-i6/i6_core/blob/e2cce78e2be5a9ad3f04cbb48d743b533aaf628b/recognition/scoring.py#L154
I assume the job would fail if the sclite call has a nonzero return status. So my guess is, that sclite did not correctly report a failure.

So first I would verify these assumptions and then check if sclite has an option to fail more rigorous.

**Comment by Atticus1806** [comment]
`/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/recognition/scoring/ScliteJob.BBz1rjczzsEc/input/i6_core_recognition_conversion_LatticeToCtmJob.95iKcvijTuix/` 
this is from another failed ScliteJob but should be the same.
And this is the Sclite job:
`/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/recognition/scoring/ScliteJob.BBz1rjczzsEc/`

**Comment by Atticus1806** [comment]
Small update: This indeed seems to be a bug in the `LatticeToCtmJob`. The merge task does not properly merge the different files, resultling (in the example) in only part 5-10 to be merged. Rerunning merge indeed gives the correct file.
I am currently investigating why this happens.

**Comment by Atticus1806** [comment]
>check if sclite has an option to fail more rigorous.

So I could not find an option for this unfortunately, not sure if this was the right place to search though: 
https://htmlpreview.github.io/?https://github.com/usnistgov/SCTK/blob/master/doc/options.htm

So there are a few options now. Either way we need to fix the `LatticeToCtmJob`. Still I would think we should do some check that this align error does not happen during the job. Maybe some `grep` on the log checking for `align_ctm_to_stm` (fom my understanding this only comes when there is an error there). 
Maybe other ideas?

**Comment by Atticus1806** [comment]
I opened a first PR to fix (or catch) the probelm in the LatticeJob. Nevertheless this should also be caught in the ScliteJob somehow in my opinion.
