### ISSUE TITLE
Extra Requirements in GMM Trainings

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/i6_core#354]
After looking at some crashed jobs I found some lets say unusual values for requirements like GB in my GMM jobs (10, 7, 5). 
Short investigation found that the parameters `"*_extra_rqmt"` do not replace the requirement, but rather add the requirements to the basic rqmt (c.f. `udpate_rqmt` in mm_sequence.py).
After talking to @JackTemaki we conlcuded that this is somewhat surprising and usually done differently, where handin rqmt  to a job in the construction would replace the rqmt not add it. 

In general this is no big deal, but for me the values in the baseline rather look like intended replacement values and not added values I just wanted to bring this up, because we might be able to save resources in the future with reducing some of them.

**Comment by michelwi** [comment]
I think that is why it is called `*_extra_rqmt` and not `*_rqmt`.

I was fully aware of that peculiarity, but agree that this could be surprising. Maybe we add the same parameters but without "extra" and those set the given value?

**Comment by Atticus1806** [comment]
I agree that the naming is somewhat clear. Maybe adding a docstring would help.
Still I wanted to bring to attention that the default added values like here 
https://github.com/rwth-i6/i6_experiments/blob/d3437fe498874ec69141278d9ac1848e2f33fd16/common/baselines/librispeech/ls100/gmm/baseline_args.py#L208 
is 8, which to me rather seems like this was inteded to be 8 in total.

For example for the ls960 pipeline this value is 6, https://github.com/rwth-i6/i6_experiments/blob/d3437fe498874ec69141278d9ac1848e2f33fd16/common/baselines/librispeech/ls960/gmm/baseline_args.py#L218, so here it might be "correct", or is this difference intended?

Maybe @christophmluscher or @JackTemaki can comment? 

In general this issue was not about a faulty behavior or necessarily a change, but just to start a discussion on whether this behavior is known/intended.
