### ISSUE TITLE
Change black formatting to 120 chars?

### ISSUE THREAD

**Issue by albertz** [rwth-i6/i6_core#362]
This is the default we always had in RETURNN, also in returnn-common, and pretty universal (also default in PyCharm).

Corresponding issue in i6_experiments: https://github.com/rwth-i6/i6_experiments/issues/118

**Comment by albertz** [comment]
It was briefly mentioned (but not really discussed) here: https://github.com/rwth-i6/i6_core/pull/17 https://github.com/rwth-i6/i6_core/issues/5

**Comment by JackTemaki** [comment]
@curufinwe @michelwi 

I would vote for 120.

**Comment by christophmluscher** [comment]
120 :)

**Comment by michelwi** [comment]
sure.. why not.. 🤷

**Comment by curufinwe** [comment]
No objections from my side.
