### ISSUE TITLE
Beginning of stable period

### ISSUE THREAD

**Issue by curufinwe** [rwth-i6/i6_core#38]
We wanted to be finished with setup/hash breaking changes by end of May. That's today. Does anyone of you have more breaking changes that you'd like to integrate? If so, should we agree on a timetable until when these changes need to be done?

**Comment by mmz33** [comment]
Yes I still need to fix the BPE train and apply jobs. We agreed to use a fixed commit hash for `CloneGitRepository`. I can do a PR for that soon.

**Comment by JackTemaki** [comment]
Yes, also for me there are more jobs incoming. I would say (with looking at the upcoming holidays) we need at least 2 more weeks.

**Comment by christophmluscher** [comment]
@JackTemaki new jobs or refactoring?
new jobs should not influence beginning of stable period in my opinion

**Comment by JackTemaki** [comment]
There is something that needs to be fixed for the RETURNN hashes, so definitely critical.

**Comment by christophmluscher** [comment]
the 2 weeks factors in ICASSP?

**Comment by JackTemaki** [comment]
> the 2 weeks factors in ICASSP?

Ah right...

**Comment by curufinwe** [comment]
We could also do this in two stages:
1. no breaking hashes but may need to refactor setups
2. setups must run without modification

**Comment by christophmluscher** [comment]
I think the points raised here, have been addressed. Are they completed now?
Or are there still hash breaking changes missing?

**Comment by mmz33** [comment]
From my side, I think all jobs needed to train/recognize attention models at least are merged except for the BPE jobs which are in PR currently.

**Comment by curufinwe** [comment]
Actually I also want to make a few changes to the recognition job. Would June 18th as a final stop on hash breaking changes be OK? (1 week after ICASSP).

**Comment by JackTemaki** [comment]
As @mattiadg  and @papar22 started using this actively and pointed out some bugs, I propose that we extend the duration by one more week. @curufinwe what do you think?

**Comment by curufinwe** [comment]
OK

**Comment by curufinwe** [comment]
The time has come and nobody asked for another extension. Thus we can no go to a more stable regime where changes must not break existing hashes. Thanks to everyone contributing to the refactoring effort!
