### ISSUE TITLE
Remove stale, merged, closed branches

### ISSUE THREAD

**Issue by christophmluscher** [rwth-i6/i6_core#397]
Can we cleanup all branches which are:
- stale
- merged
- closed
?

@Atticus1806 @mattiadg @JackTemaki @michelwi @vieting @curufinwe

**Comment by JackTemaki** [comment]
branches are clean, for rest I need to ping people, this is better for a monday morning than a friday afternoon :)

**Comment by Atticus1806** [comment]
I think I cleaned mine a few days ago.

**Comment by michelwi** [comment]
I cleaned the one branch with a `willi` prefix. Thank for reminder. 👍

**Comment by JackTemaki** [comment]
We are down to 9 branches now, I guess we can close
