### ISSUE TITLE
BlissChangeEncodingJob might return wrong audios if it crashes

### ISSUE THREAD

**Issue by Icemole** [rwth-i6/i6_core#402]
Hi all! I used `i6_core.audio.encoding.BlissChangeEncodingJob` to convert some audios from 8kHz to 16kHz, but after using the output of the job in successive feature extraction jobs, I noticed that at least an output audio was way shorter than its 8kHz counterpart.

I tracked this error and I found that while [`ffmpeg` is executed with the `-y` flag](https://github.com/rwth-i6/i6_core/blob/main/audio/ffmpeg.py#L189) which overwrites the output file, the call to `ffmpeg` is wrapped by [a conditional that checks if the file exists](https://github.com/rwth-i6/i6_core/blob/main/audio/ffmpeg.py#L184), practically making the `-y` flag useless.

The key issue is that my job had run out of resources (time), and therefore it had been terminated and run again. As I see it, the conflictive output audio was unfortunately being processed while the job termination was happening. Therefore, it was saved with the duration that `ffmpeg` had time to process before it was abruptly terminated, but this implies that the output file had been already created, effectively bypassing the overwrite that should have happened because the `if` was evaluated to `True`.

**Comment by michelwi** [comment]
So the Job does not correctly handle interruptions and resuming at the correct position. We could either
1. check for audio file duration << reference duration 
2. mark the job as non-resumable

but I fear that with certain kinds of length perturbation schemes, we will run into problems with 1.

**Comment by Icemole** [comment]
Doesn't the `BlissChangeEncodingJob` only change the sampling rate, number of channels or other similar parameters that don't affect the duration? As long as the input audio doesn't get speed-perturbed (for instance) inside the job, then there would be no issue with 1, right?

Anyway, I'd agree on marking the job as non-resumable. As I see it, right now the job is not resumable because of the problems that derive from this issue.

**Comment by JackTemaki** [comment]
I also think making it non-resumable is the safest option for now. There can always be problems during the interrupt, and checking the files might not be easy (different compression types can have a slightly varying duration).
