### ISSUE TITLE
Usage of `Literal`

### ISSUE THREAD

**Issue by christophmluscher** [rwth-i6/i6_core#408]
Here a `Literal` from `typing` is used:

https://github.com/rwth-i6/i6_core/blob/e3ea366746eab8c7639ff680d40ce49a6870b6c5/am/config.py#L11

 but this is only available from Python 3.8+

Bump Python version to 3.8? Or handle it via `typing_extensions`? Or remove `Literal`?

Currently this leads to a failed test in PR: #407

@JackTemaki @SimBe195 @curufinwe @Atticus1806 @michelwi

**Comment by christophmluscher** [comment]
I have a solution via try except but I would prefer bumping Python to 3.8.

**Comment by SimBe195** [comment]
I'd be in favor of using Python 3.8.

**Comment by JackTemaki** [comment]
I am also Voting for Python 3.8

**Comment by michelwi** [comment]
+1 for 3.8.

**Comment by christophmluscher** [comment]
closed with #409
