### ISSUE TITLE
Double if in PrecomputedHybridFeatureScorer

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/i6_core#418]
Is there a reason this is checked twice or can one be removed? 

https://github.com/rwth-i6/i6_core/blob/5fd3f6ad6f696c8a5bccc4d4426e7032c84c0519/rasr/feature_scorer.py#LL123-L127

Edit: I am not sure why the lines are not visible here

**Comment by michelwi** [comment]
looks very redundant to me. You may git blame and ask whoever did that, or just remove 🤷
