### ISSUE TITLE
FairseqHydraTrainingJob has mutable default argument

### ISSUE THREAD

**Issue by vieting** [rwth-i6/i6_core#470]
The `FairseqHydraTrainingJob` currently has `rqmt={"gpu": 1, "cpu": 2, "mem": 4, "time": 4}` by default which is a dict, thus mutable and discouraged as default argument. Should we fix that? Just put `None` there and if `rqmt is None` set it to that dict again? What about the hash behavior? Is there a way to keep the hashes? This is not the typical use case of `__sis_hash_exclude__`, right?

**Comment by michelwi** [comment]
> Should we fix that? Just put None there and if rqmt is None set it to that dict again? 

Yes

> What about the hash behavior? Is there a way to keep the hashes? 

This class already has an [overridden hash function](https://github.com/rwth-i6/i6_core/blob/11fb91b5c45e6092461872c57115e23dd956a8ce/fairseq/training.py#L477-L484) which does not take the rqmt into account. So just changing it should be fine. (But pls test just to be sure..)

**Comment by vieting** [comment]
Yes, you're right. I tested and created #472.
