### ISSUE TITLE
Hash Breaks in HeadJob

### ISSUE THREAD

**Issue by vieting** [rwth-i6/i6_core#478]
In #467, there are modifications to the `HeadJob`, in particular:
```
-        self.out = self.output_path("out.gz")
+        self.out = self.output_path("out.gz") if self.zip_output else self.output_path("out")
```
In general, this makes sense of course. However, it breaks setups that use this job with `zip_output=False` because (a) if the job did already run, subsequent jobs will now look for the output file `"out"` which does not exist (only `"out.gz"` exists) and (b) subsequent jobs will have different hashes because of the changed input.

In particular, I have a setup which has a `TailJob` (inherits this issue from `HeadJob`) as input to returnn trainings (segment list). Now, all trainings would re-run. Since the change in general makes sense, I wouldn't necessarily revert it though. A fix for my case would be to reassign the out file.
```
tail_job = text.TailJob(train_segments, num_lines=300, zip_output=False)
tail_job.out = tail_job.output_path("out.gz")
```
This is a bit hacky though and sisyphus outputs warnings:
```
WARNING: Added output out.gz more than once to Job<work/i6_core/text/processing/TailJob.RiSM6fe2XipO>
```

What do you guys think?

**Comment by vieting** [comment]
Maybe also @jairsan as the author of #467 wants to comment.

**Comment by michelwi** [comment]
can we add a hash_overwrite? e.g.
```
self.out = self.output_path("out.gz") if self.zip_output else self.output_path("out")
self.out.hash_overwrite = (this, "out.gz")
```

cf https://github.com/rwth-i6/sisyphus/blob/399b8d9a73c934ea57cd61bc472711e127a2bce9/sisyphus/job_path.py#L129-L134 and https://github.com/rwth-i6/sisyphus/blob/399b8d9a73c934ea57cd61bc472711e127a2bce9/sisyphus/job_path.py#L85-L98

**Comment by vieting** [comment]
> self.out.hash_overwrite = (self, "out.gz")

I just tested this and can confirm that it works. It's generally not really nice to have that in the init imho, but if we follow rule 1 and 2 from the [contribution guidelines](https://github.com/rwth-i6/i6_core/blob/main/CONTRIBUTING.md), I guess not breaking the hashes outweighs that argument.
> 1. Don't break a jobs hash
> 2. Really don't break a jobs hash
