### ISSUE TITLE
`i6_core.serialization` cannot serialize `int`

### ISSUE THREAD

**Issue by Icemole** [rwth-i6/i6_core#513]
Hi all, I'm trying to use `i6_core.serialization.PartialImport` in order to serialize a partial function which gets as parameter a dataset with typing `Dict[str, Any]` and returns a slightly modified version of the dataset (for additional context, see https://github.com/rwth-i6/returnn/issues/1540).

I know that the dictionary that represents the dataset would only be composed of primitive data types (because I control the return values), among which there's an int that represents the `partition_epoch` parameter. However, when parsing the dictionary and reaching the part where the int is defined, I get the following error:

```
File .../recipe/i6_core/returnn/config.py:307, in <genexpr>(.0=<dict_itemiterator object>)
    305     return "\n".join(self.__parse_python(c) for c in code)
    306 if isinstance(code, dict):
--> 307     return "\n".join(self.__parse_python(v, name=k) for k, v in code.items())
        self = <i6_core.returnn.config.ReturnnConfig object at 0x7f0304a79150>
        v = 75
        k, v = ('partition_epoch', 75)
        k = 'partition_epoch'
    308 if inspect.isfunction(code):
    309     try:

File .../recipe/i6_core/returnn/config.py:339, in ReturnnConfig.__parse_python(self=<i6_core.returnn.config.ReturnnConfig object>, code=75, name='partition_epoch')
    337 if inspect.isclass(code):
    338     return inspect.getsource(code)
--> 339 raise RuntimeError("Could not serialize %s" % code)
        code = 75
        "Could not serialize %s" % code = 'Could not serialize 75'
```

I can share with you the full stack trace, but for me what's happening is clear: the final dataset dictionary is trying to be serialized, it gets to the part where `__parse_python()` is called with the dict ([here](https://github.com/rwth-i6/i6_core/blob/main/returnn/config.py#L293)), tries to serialize `partition_epoch` ([here](https://github.com/rwth-i6/i6_core/blob/main/returnn/config.py#L307)) and fails to parse the int because it's not a recognized class to serialize according to `__parse_python()`.

Has anyone faced this issue? If so, what are you doing to fix this approach?

**Comment by albertz** [comment]
How exactly are you using it? Can you show the code?

**Comment by albertz** [comment]
Also can you post the full stack trace? I don't see how it gets there.

**Comment by JackTemaki** [comment]
@Icemole are you using it in combination with a `Collection`? I am not sure what happens if you use it as-is, it was never intended for that.

**Comment by JackTemaki** [comment]
So for me it seems that you put a normal dictionary in python_prolog or python_epilog, this will not work. Only strings and nested objects that can be resolved into strings are supported, as this is about writing code as string directly into the config.
