### ISSUE TITLE
Add output_mode parameter to ReturnnSearchJob as in ReturnnSearchFromFileJob

### ISSUE THREAD

**Issue by jvhoffbauer** [rwth-i6/i6_core#55]
I think it would make sense to add an `output_mode` parameter to `ReturnnSearchJob`. `ReturnnSearchFromFileJob` has this parameter already and it specifies whether Returnn outputs the search result in `'txt'` or `'py'` mode. 

Currently `ReturnnSearchJob` has `'py'` as default, while Returnn uses `'txt'` as its default. This can lead to problems when migrating a pipeline. So I would also think about changing the default to `'txt'`

**Comment by curufinwe** [comment]
First part sounds OK to me. Second part would break already existing sisyphus setups, so we'd have to do it this week or not at all.
@mmz33 @JackTemaki  thoughts?

**Comment by JackTemaki** [comment]
The default was `py` because `ReturnnComputeWERJob` (direct WER), and `SearchWordsToCTMJob`  (for sclite WER) need the py format, so I do not think it is a good idea to have 'txt' as default, even if this is the case for RETURNN.

**Comment by christophmluscher** [comment]
>  Second part would break already existing Sisyphus setups

I think both parts would break the hash or not? Or do we want to include `__sis_hash_exclude__` already?

@jvhoffbauer which pipelines are using `txt` format?

**Comment by mmz33** [comment]
I would also agree with @JackTemaki . I am not sure what you mean here by migrating a pipeline. You would need to use the jobs in this repo which are consistent with `py` format.

**Comment by JackTemaki** [comment]
Yes both parts would break the hash, but I think adding the option for the output format is fine (when done this week).

**Comment by jvhoffbauer** [comment]
Ok. I will commit today.

**Comment by jvhoffbauer** [comment]
> I would also agree with @JackTemaki . I am not sure what you mean here by migrating a pipeline. You would need to use the jobs in this repo which are consistent with py format.

I just wanted to point out, that the Returnn and the recipe default are different here and this might be unintuitive. But anyways, I also think the py output format should be the default as it is easier to parse and integrates with he rest of the i6_core recipes.

**Comment by curufinwe** [comment]
> @JackTemaki I agree.
> 
> So adding the option: yes. Changing the default: no. @curufinwe yes?
> 
> @jvhoffbauer can you make the pull request today or tomorrow?

correct

**Comment by christophmluscher** [comment]
> Yes both parts would break the hash

I think I was wrong the first part only breaks the hash with a change from "py" to "txt", since the py/txt flag is included in the config variable for hash calculation
