### ISSUE TITLE
How to handle create_returnn_config call from ReturnnRasrTrainingJob

### ISSUE THREAD

**Issue by Marvin84** [rwth-i6/i6_core#71]
Calling `create_returnn_config` at [this](https://github.com/rwth-i6/i6_core/blob/main/returnn/rasr_training.py#L280) point results in an error, since `horovod_num_processes` has to be passed as an argument. This call within `ReturnnTrainingJob` is not problematic, since it relies on arguments that are taken from the class attributes, and `horovod_num_processes` is in this case part of them.
There are two solutions to this.
(1) Set `horovod_num_processes` to have default value of `None` in the function call.
(2) Handle this internally to `RasrReturnnTrainingJob` by either adding a new attribute to the class or setting it manually before calling the function, with value `None`. In this case, the question is: can/do we use this parameter for a training job that relies on RASR? If yes, I  propose that we add this as a class attribute.

Please let me know your thoughts: @curufinwe @JackTemaki @dthulke

**Comment by dthulke** [comment]
Sorry for missing this.

(1) Would be the simplest solution. Maybe it makes even sense to move remove this as a param and check it via kwargs in the function.
(2) Not sure whether there is a reason `horovod_num_processes` is missing in the rasr training job. Are there any incompatibilities? If not, it should also be added to the `RasrReturnnTrainingJob`.

**Comment by michelwi** [comment]
> (2) Not sure whether there is a reason `horovod_num_processes` is missing in the rasr training job. Are there any incompatibilities?

Not that I know of

> If not, it should also be added to the `RasrReturnnTrainingJob`.

Yes I agree this should be the preferred solution: Add the option `horovod_num_processes` with default `None` to the `__init__` of the `RasrReturnnTrainingJob` to enable multi-GPU training.

**Comment by curufinwe** [comment]
Resolved by #72
