### ISSUE TITLE
import cachemanager in recognition/optimize_parameters.py

### ISSUE THREAD

**Issue by mattiadg** [rwth-i6/i6_core#75]
`recognition/optimize_parameters.py:69` has `import cachemanager`.

Apparently it refers to https://github.com/rwth-i6/cache-manager. It would be nice to have the dependency documented somewhere.

**Comment by curufinwe** [comment]
Yeah, this is a leftover from the time when Path.cached meant that we use the i6 cache-manager. Now it is user configurable and often the configuration is: don't do any caching.

**Comment by mattiadg** [comment]
Can it be just removed then?

**Comment by curufinwe** [comment]
Yes, for now it's probably the best solution. Long term we should rethink the way caching works in the recipes.
