### ISSUE TITLE
global variable of SCTK_PATH does not parse

### ISSUE THREAD

**Issue by papar22** [rwth-i6/i6_core#76]
In the scoring.py in ScliteJob, the path to the binary is not propagated.
https://github.com/rwth-i6/i6_core/blob/main/recognition/scoring.py#L91

Maybe adding it to the PATH env does the job. Like:
```
if hasattr(gs, "SCTK_PATH"):
    os.environ["PATH"] = gs.SCTK_PATH + ":" + os.environ["PATH"]
```

**Comment by michelwi** [comment]
The line you indicated should add the contents of `SCTK_PATH` as defined in sisyphus global settings to the `sclite_path`.

Can you please tell us, what values `gs.SCTK_PATH` and `sclite_path` have and what the call that is finally done (cf. log file) looks like?

**Comment by mattiadg** [comment]
I'm working with a similar config and I got the same error. This is the info:
`gs.SCTK_PATH = '/library/data4/tools/sctk-2.4.10/bin/'`
but `sclite_path` contains just `sclite`, meaning that it couldn't find `gs.SCTK_PATH`.

The final error for me is
`FileNotFoundError: [Errno 2] No such file or directory: 'sclite': 'sclite'`

**Comment by michelwi** [comment]
so you mean at this point in the code `print(gs.SCTK_PATH)` will print the value you indicated, but `hasattr(gs, "SCTK_PATH")` is `False` ?

**Comment by mattiadg** [comment]
No, I assign it in my config but then the value it's not propagated up to the point mentioned in the issue.

**Comment by JackTemaki** [comment]
@mattiadg can you move the code that assigns the sclite_path to the `__init__` as class member, then delete the job and try again? Just a hunch I have...

**Comment by JackTemaki** [comment]
> No, I assign it in my config 

Oh, this can not work. `gs` is a global variable from sisyphus. When you set `gs.SCTK_PATH` in the config, this means the gs gets set for the manager process only. The `run` method is called from the worker, meaning it uses a "fresh" gs from the `settings.py`. You should never write stuff into the `gs`object.

**Comment by JackTemaki** [comment]
The correct solution here would be to give the path as job parameter, just as all other external software dependent jobs do it, I will fix that.

**Comment by michelwi** [comment]
> can you move the code that assigns the sclite_path to the `__init__` as class member,

>  I will fix that.

just make sure, that the absolute path is not written into the hash if not given explicitly.

@mattiadg the easiest solution would be to instead set 
`SCTK_PATH = '/library/data4/tools/sctk-2.4.10/bin/'`
in your `settings.py` if that is possible.

**Comment by mattiadg** [comment]
Regarding the last comment, if I create variables like `SCTK_PATH = '/library/data4/tools/sctk-2.4.10/bin/'` in my settings, do they get added automatically to gs? 
If yes, how does it work? Is there a fixed set of names or are all the capitalized variables to be added?

**Comment by curufinwe** [comment]
everything that is defined in settings.py is part of `gs`. Capitalization is just a convention.

**Comment by michelwi** [comment]
the content of `settings.py` overwrites the settings in global_settings. Anything can be overwritten and anything new will be added.

e.g. the `SCTK_PATH` is in fact not required by sisyphus, but added by our recipes. You could also add a new `my_custom_variable` and access it in your own recipes.

As the `settings.py` is read by the manager AND by the worker, all variables you define there will also be available at runtime of the Job - which was not the case when you only added it in your config within the manager.
