### ISSUE TITLE
create_dataset_config assuming dict keys

### ISSUE THREAD

**Issue by mattiadg** [rwth-i6/i6_core#78]
In the recently modified code https://github.com/rwth-i6/i6_core/blob/7f02b0fbda90480d42b3d5488e10b714ddabeb06/returnn/rasr_training.py#L249-L254 we are checking that `partition_epoch` is not in `returnn_config.config["train"]` and `returnn_config.config["dev"]` but we have no guarantees that `train` and `dev` exist in `returnn_config.config`, thus causing an error.

**Comment by curufinwe** [comment]
Resolved in #79
