### ISSUE TITLE
Not delayed path computation of Checkpoint

### ISSUE THREAD

**Issue by mattiadg** [rwth-i6/i6_core#83]
I'm using the `Checkpoint` class for referring to the model checkpoints for recognition.
The path stored in `self.index_path` causes the following warning in Sisyphus:
`Creating absolute path inside current work directory: /path/to/work/i6_core/returnn/rasr_training/ReturnnRasrTrainingJob.N1l7gLewoOqw/output/models/epoch.001.index`

Followed by an `input_missing` error:
`ERROR: input_missing: /path/to/work/i6_core/returnn/rasr_training/ReturnnRasrTrainingJob.N1l7gLewoOqw/output/models/epoch.001.index`

if I try to create define `index_path` as a `Delayed` object, such as `DelayedBase` or `DelayedFormat`, sisyphus crashes because the function highlighted in here

https://github.com/rwth-i6/i6_core/blob/9c5d66010b84dd18b3631e473c6bb2953841616f/returnn/training.py#L52-L53

requires that `self.index_path` has a `_sis_hash()` method.

When the checkpoint is created, then the dependent jobs are executed, but it's really annoying to have this long list of of error messages every time a job is submitted or finishes.

Maybe it's not `Checkpoint` to create the problem, but the warning and errors are clearly referring to the path in that variable, so I think there are not many doubts.

**Comment by JackTemaki** [comment]
I do not think this is related to the checkpoint, because I am also using it without getting this warning with other recognition jobs. Also I am sure you did not want to have  `/path/to/work/i6_core/returnn/rasr_training/ReturnnRasrTrainingJob.N1l7gLewoOqw/output/models/epoch.001.index` as input to a job, so there is something else going on...

**Comment by JackTemaki** [comment]
After reviewing the config code, there was an issue in the given setup with manual paths created during the graph execution, as e.g.

```
checkpoint = Checkpoint(
          '%s/epoch.%03d' % (checkpoint_dir, epoch),
          tk.Path('{}/epoch.{:03d}.index'.format(checkpoint_dir, epoch)),
        )
```

This means that a new Path is created independent of a Job as creator, and the Path variable is resolved to string during the graph creation, which can lead to severe errors.

As a general recommendation the warning `Creating absolute path inside current work directory` should be considered an error. Always look out for a location where a Path object is accidentally converted into a string during graph construction.
