### ISSUE TITLE
Cached lattices in OptimizeAMandLMScaleJob

### ISSUE THREAD

**Issue by vieting** [rwth-i6/i6_core#91]
#80 removed the hard-coded reference to the cache manager from the `OptimizeAMandLMScaleJob`. Now, if the lattice path is a `Path` object with `cached=True`, we end up with a string as expected in `self.run_script`. However, the `subprocess.check_call` does not seem to handle it correctly, I assume because of the space in `cf /u/...`.

I end up with the error
>   Archive file "`cf" does not exist.

**Comment by JackTemaki** [comment]
close with #92
