### ISSUE TITLE
ReturnnTrainingJob hashes with function in python_prolog

### ISSUE THREAD

**Issue by vieting** [rwth-i6/i6_core#93]
Assume I am running a `ReturnnTrainingJob` and the `ReturnnConfig` has a `python_prolog` which is a dict which contains a function, e.g. in my case the function `get_network()` which is defined in a helper file. This function is serialized to be written in the config file, however, not for creating the hash. So if I change something in the function, the hash remains unchanged while the behavior in RETURNN would obviously be very different.

From my perspective, it would be intuitive if the hash changes when changing the function. This would have the drawback that if you add a new argument to the function which does not change the behavior when the default value is used, still all hashes change. But for this, you might consider using `python_prolog_hash`.

What do you guys think?

**Comment by michelwi** [comment]
But in https://github.com/rwth-i6/i6_core/blob/e0971f14f43a1d73ca0fa4965ff775fcd72cb16d/returnn/config.py#L95-L97 the `python_prolog_hash` is set to the `python_prolog` so it should be considered for hashing. 

Ah, but if you hand a function object instead of the actual source code, then maybe this object serializes (for the purpose of hashing) always the same even if you change the code.

So we should instead use 
```
        self.python_prolog_hash = (
            python_prolog_hash if python_prolog_hash is not None else self.__parse_python(python_prolog)
        )
```
which would keep the hash of all text-based `python_prolog`'s intact.

**Comment by vieting** [comment]
Exactly, something like this would be my suggestion. However, I wasn't sure if the current behavior was intended. (And this change would break some hashes.)

**Comment by michelwi** [comment]
I think this behavior was not intended. And it should imho be consistent for text-based and function-object-based prologs.

So I'd say go forward with a PR (and don't forget the epilog)

**Comment by JackTemaki** [comment]
> I think this behavior was not intended

The problem is this behavior was indeed intended, and nobody complained about it. So the idea was to either change the function name (= new hash) or do it manually.

**Comment by JackTemaki** [comment]
it is true that nobody changed the "status: unstable" yet (I guess I should do that), but we did not want to break the hashes anymore, which this change will definitely do.... I think for the Optimize Job this was an exception, because there was a crash in certain cases and it comes usually at the end of pipelines...

**Comment by curufinwe** [comment]
It was not intended from my side. I assumed that sisyphus would handle hashing of functions correctly.

**Comment by curufinwe** [comment]
And actually it does (sort of): https://github.com/rwth-i6/sisyphus/blob/b73579fe91800192ca918225092582768d73613a/sisyphus/hash.py#L102

**Comment by curufinwe** [comment]
@vieting where are your functions defined?

**Comment by vieting** [comment]
>@vieting where are your functions defined?

In a helper in `i6_private`. In the config, I do `from i6_private.users.vieting.helpers.wav2vec2 import get_network`, and then I set `python_prolog = {"get_network": get_network}`

**Comment by vieting** [comment]
>it is true that nobody changed the "status: unstable" yet

Actually this was done with #38. So yes, this change would change many hashes and I could also handle these cases manually.

**Comment by JackTemaki** [comment]
> And actually it does (sort of): https://github.com/rwth-i6/sisyphus/blob/b73579fe91800192ca918225092582768d73613a/sisyphus/hash.py#L102

But this does not hash the function content, as I stated before.

> Actually this was done with #38.

It was not changed on the title page, this is what I referred to...

**Comment by curufinwe** [comment]
> But this does not hash the function content, as I stated before.
I guess the assumption is that functions remain the same. If you were to change the name of the function it should change. So this is mainly a problem when developing a new setup.

**Comment by vieting** [comment]
So I guess I'll close the issue and take care of this manually.
